# Generated by Django 5.2.7 on 2025-10-17 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SettingsConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('sub_title', models.CharField(blank=True, max_length=500, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('icon', models.ImageField(blank=True, default='default/site_icon.png', null=True, upload_to='site/')),
                ('logo', models.ImageField(blank=True, default='default/site_logo.png', null=True, upload_to='site/')),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('stage', models.CharField(blank=True, choices=[('Basic', 'Basic'), ('Medium', 'Medium'), ('Advanced', 'Advanced')], max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SocialMediaURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('website', 'Website'), ('instagram', 'Instagram'), ('twitter', 'Twitter'), ('linkedin', 'Linkedin'), ('github', 'Github'), ('youtube', 'Youtube')], default='facebook', max_length=20)),
                ('url', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Team_Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('professional_title', models.CharField(max_length=255)),
                ('phone_number', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(blank=True, default='default/default_team_member_image.png', null=True, upload_to='team_member/prof/')),
                ('cover_image', models.ImageField(default='default/default_team_member_cover_image.jpg', upload_to='team_member/cover/')),
                ('designation', models.CharField(blank=True, max_length=200, null=True)),
                ('short_description', models.TextField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=10, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('skills', models.ManyToManyField(blank=True, to='core.skills')),
            ],
        ),
    ]
