# Generated by Django 5.2.7 on 2025-10-19 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='settingsconfig',
            name='call',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
    ]
