# Generated by Django 5.2.7 on 2025-10-20 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_settingsconfig_call'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField(default=1)),
                ('text', models.CharField(blank=True, max_length=255, null=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('url', models.URLField(blank=True, max_length=255, null=True)),
                ('slide', models.ImageField(blank=True, null=True, upload_to='slide/')),
                ('is_active', models.BooleanField(default=True)),
                ('create_at', models.DateTimeField(auto_now=True)),
                ('update_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='skills',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='skills',
            name='stage',
            field=models.CharField(blank=True, choices=[('Basic', 'Basic'), ('Medium', 'Medium'), ('Advanced', 'Advanced')], default='Medium', max_length=10, null=True),
        ),
    ]
