# Generated by Django 5.2.7 on 2025-10-20 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about_me', '0001_initial'),
        ('team_member', '0002_teammember_cv'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='About_Me',
            new_name='AboutMe',
        ),
    ]
