# Generated by Django 5.2.7 on 2025-10-20 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_me', '0002_rename_about_me_aboutme'),
        ('team_member', '0003_alter_teammember_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='SliderTagList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='team_member.teammember')),
            ],
        ),
    ]
