# Generated by Django 5.2.7 on 2025-10-20 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_me', '0003_slidertaglist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutme',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
