# Generated by Django 5.2.7 on 2025-10-20 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_me', '0004_alter_aboutme_address'),
        ('team_member', '0003_alter_teammember_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slidertaglist',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slider_tags', to='team_member.teammember'),
        ),
    ]
