# Generated by Django 5.2.7 on 2025-10-20 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about_me', '0005_alter_slidertaglist_person'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SliderTagList',
        ),
    ]
