# Generated by Django 5.2.7 on 2025-10-20 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_me', '0006_delete_slidertaglist'),
    ]

    operations = [
        migrations.CreateModel(
            name='SliderTagList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('aboutme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slider_tags', to='about_me.aboutme')),
            ],
        ),
    ]
