# Generated by Django 5.2.7 on 2025-10-22 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_me', '0007_slidertaglist'),
    ]

    operations = [
        migrations.AddField(
            model_name='slidertaglist',
            name='index',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
