# Generated by Django 5.2.7 on 2025-10-22 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_me', '0008_slidertaglist_index'),
        ('core', '0004_companyindustry_companyinformation'),
        ('team_member', '0004_remove_teamworkpicture_work_delete_teamwork_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slidertaglist',
            options={'ordering': ['index']},
        ),
        migrations.CreateModel(
            name='OurService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='service/')),
                ('icon', models.CharField(blank=True, max_length=25, null=True)),
                ('short_description', models.TextField(blank=True, null=True)),
                ('industry', models.CharField(blank=True, max_length=255, null=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_me', models.BooleanField(default=True)),
                ('create_at', models.DateTimeField(auto_now=True)),
                ('update_at', models.DateTimeField(auto_now_add=True)),
                ('skills', models.ManyToManyField(to='core.skills')),
            ],
        ),
        migrations.RenameModel(
            old_name='MyWork',
            new_name='OurWork',
        ),
        migrations.CreateModel(
            name='OurWorkPicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='work/')),
                ('is_active', models.BooleanField(default=True)),
                ('create_at', models.DateTimeField(auto_now=True)),
                ('update_at', models.DateTimeField(auto_now_add=True)),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ourworkpicture', to='about_me.ourwork')),
            ],
        ),
        migrations.DeleteModel(
            name='MyWorkPicture',
        ),
    ]
