# Generated by Django 5.2.7 on 2025-10-22 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_me', '0009_alter_slidertaglist_options_ourservice_and_more'),
        ('core', '0004_companyindustry_companyinformation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourservice',
            name='skills',
            field=models.ManyToManyField(blank=True, to='core.skills'),
        ),
    ]
