# Generated by Django 5.2.7 on 2025-10-19 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamSettingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_title', models.CharField(blank=True, max_length=500, null=True)),
                ('team_icon', models.ImageField(blank=True, null=True, upload_to='team/settings/')),
                ('team_logo', models.ImageField(blank=True, default='default/team-c-logo-transparent.png', null=True, upload_to='team/settings/')),
                ('team_email', models.EmailField(blank=True, max_length=200, null=True)),
                ('team_phone_number', models.CharField(blank=True, max_length=14, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('professional_title', models.CharField(max_length=255)),
                ('phone_number', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(blank=True, default='default/default_team_member_image.png', null=True, upload_to='team/profile_picture/')),
                ('cover_image', models.ImageField(default='default/default_team_member_cover_image.jpg', upload_to='team/cover/')),
                ('designation', models.CharField(blank=True, max_length=200, null=True)),
                ('short_description', models.TextField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('others', 'Others')], default='male', max_length=10)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(blank=True, default=True, null=True)),
                ('create_at', models.DateTimeField(auto_now=True)),
                ('update_at', models.DateTimeField(auto_now_add=True)),
                ('skills', models.ManyToManyField(to='core.skills')),
            ],
        ),
        migrations.CreateModel(
            name='TeamWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('short_description', models.TextField()),
                ('industry', models.CharField(blank=True, max_length=255, null=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('project_value', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(blank=True, default=True, null=True)),
                ('create_at', models.DateTimeField(auto_now=True)),
                ('update_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ManyToManyField(to='team_member.teammember')),
                ('skills', models.ManyToManyField(to='core.skills')),
            ],
        ),
        migrations.CreateModel(
            name='TeamWorkPicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='work/team/')),
                ('is_active', models.BooleanField(default=True)),
                ('create_at', models.DateTimeField(auto_now=True)),
                ('update_at', models.DateTimeField(auto_now_add=True)),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teamworkpicture', to='team_member.teamwork')),
            ],
        ),
    ]
