# Generated by Django 5.2.7 on 2025-10-20 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_member', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='team/cv'),
        ),
    ]
