# Generated by Django 5.2.7 on 2025-10-20 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_member', '0002_teammember_cv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='phone_number',
            field=models.CharField(blank=True, null=True),
        ),
    ]
