# Generated by Django 5.2.7 on 2025-10-22 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team_member', '0003_alter_teammember_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamworkpicture',
            name='work',
        ),
        migrations.DeleteModel(
            name='TeamWork',
        ),
        migrations.DeleteModel(
            name='TeamWorkPicture',
        ),
    ]
